# Generated by Django 5.1.2 on 2025-01-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('github_link', models.URLField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('cover_photo', models.ImageField(blank=True, upload_to='project_covers/')),
            ],
        ),
    ]
