# Generated by Django 5.1.2 on 2024-12-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='bio',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='photo',
            new_name='image',
        ),
    ]
