# Generated by Django 5.1.2 on 2024-12-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_rename_bio_teammember_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photos/'),
        ),
    ]
