# Generated by Django 5.1.2 on 2024-12-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_remove_author_name_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='publications', to='admin_dashboard.teammember'),
        ),
    ]
