# Generated by Django 5.1.2 on 2025-01-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_historicalaboutus_historicalauthor_historicalproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='projects', to='admin_dashboard.teammember'),
        ),
    ]
