# Generated by Django 5.1.2 on 2025-02-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_project_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalteammember',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
